use_frameworks!

platform :ios, '10.0'

target 'FlexTabView_Example' do
  pod 'FlexTabView', :path => '../'

  target 'FlexTabView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
